### ISSUE TITLE
Crash while searching for a recipe

### ISSUE THREAD

**Issue by awkwaRdcaRRot** [CreativeMD/InGameConfigManager#22]
I get a crash when searching for a recipe to disable.

https://pastebin.com/03cqzTHZ

Also, when I search and use 'E' (inventory keybind) it exits out of the GUI.

**Comment by CreativeMD** [comment]
This should fix it:
https://www.dropbox.com/s/tnsrhlyb0irt4ep/CreativeCore%20v1.7.2%20mc1.11.2.jar?dl=1

**Comment by awkwaRdcaRRot** [comment]
Still getting a crash when searching.

https://pastebin.com/G1LkReTd

**Comment by CreativeMD** [comment]
Oh sorry, forgot to upload the fix for IGCM, v1.1.1 should be available soon and fix this bug. If not just reopen this issue. Thanks for reporting.
